name: Parallel Pipeline

on:
  push:
    branches:
      - cicd

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: ls -la

  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show index file
        run: cat index.html

  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: ls -la

  job4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show index file
        run: cat index.html
