name: Deploy to EC2

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a Linux command
        run: ls -la

name: Deploy to EC2

on:
  push:
    branches:
      - cicd

jobs:
  deploy2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a Linux command
        run: cat index.html